### ISSUE TITLE
Could this crate also define AsyncRead and AsyncWrite equivalents using the new types?

### ISSUE THREAD

**Issue by FrankReh** [nrc/owned-buf#11]
Would it be appropriate for this crate to also define equivalents of [AsyncRead](https://docs.rs/tokio/latest/tokio/io/trait.AsyncRead.html) and [AsyncWrite](https://docs.rs/tokio/latest/tokio/io/trait.AsyncWrite.html)?

I was curious which concrete buffer types would make up the input and output, and how the implicitly returned read or write *length* parameter is gleaned.

**Comment by nrc** [comment]
Yes, sort of. There is a design for async Read and Write traits using this buffer, specifically for io_uring, iocp, and similar: https://github.com/nrc/portable-interoperable/tree/master/io-traits#owned-read. The concrete buffer type is up to the user. The length parameter is going to be the `filled` length in the owned buffer (if it is not possible how to get that, then it might be a bug in the design.)

**Comment by FrankReh** [comment]
Thanks for the link.
