### ISSUE TITLE
Owned{Buf, Slice, Cursor} questions

### ISSUE THREAD

**Issue by FrankReh** [nrc/owned-buf#6]
One or more questions about the source as of Nov 29 '22.

**Comment by FrankReh** [comment]
Would buf.init be more appropriate than buf.filled in this cleanup?

https://github.com/nrc/owned-buf/blob/dd0fb41aeca08fd1146c8a0847d9c277cb91cbc5/src/lib.rs#L225-L235

**Comment by FrankReh** [comment]
Does this new 3-struct design cover the known completion-based Read and Write trait problems? I'm tempted to try adapting a part of tokio-uring to use these types. Also wonder what the write_all and read_exact helper functions would look like.

**Comment by nrc** [comment]
> Would buf.init be more appropriate than buf.filled in this cleanup?

I don't think it matters since here the Vec is dropped straight away and u8 has no dtor so efectively nothing is done with the length. In general, I think it is better to use `filled` for the length of the Vec and `init` for the portion of the Vec's capacity which has been initialized but not used otherwise.

> Does this new 3-struct design cover the known completion-based Read and Write trait problems?

I hope so!

> Also wonder what the write_all and read_exact helper functions would look like.

I think these are pretty trivial - just repeatedly call write/read, re-slicing in the write case and advancing the cursor
in the read case

**Comment by FrankReh** [comment]
Does the design of Vec and its drop (RawVec's drop) allow the OwnedBuf to transform itself into an owned Vec where the OwnedBuf's drop would eventually be called by a pseudo Allocator that was handed to the Vec as the Vec was pieced together? Then the Vec could live for quite some time in the workings of a higher create, even if the original buffer didn't start as a Vec.

Or better, if the backing store did come from a Vec, there could be a way to transform it back to a Vec with its original Allocator - and maybe the OwnedBuff allocator's free looks like the Vec's so the OwnedBuf can be converted to a Vec with zero cost.I don't fully understand the RawVec drop method where it calls self.current_memory first to get the ptr and the layout, what's the layout for? 

Or better, maybe  dropping an OwnedBuf could be like dropping a Vec, so they would be interchangeable as the owned object goes out of scope.

**Comment by nrc** [comment]
I'm not quite sure about these questions. Let me go over the OwnedBuf lifecycle and hopefully that will clear things up.

You can't create an OwnedBuf from nothing. You start with a `Vec` or any other owned owned datatype with sequential storage. For `Vec` there is already a `From` impl, so you call `.into()` to get an OwnedBuf. For other data types you would implement your own `From` or a utility function using `OwnedBuf::new`. The allocator generic parameter of the `OwnedBuf` would follow from the original data type.

Then you use the `OwnedBuf`, this would probably include being converted into an `OwnedSlice` or `OwnedCursor` and perhaps back again.

You might then convert the `OwnedBuf` back into it's original datatype. For `Vec`, you call `into_vec` or `into_uninit_vec`. For other data types you'd have to provide a utility function. The Vec or whatever gets dropped at some point as usual.

Alternatively, if the `OwnedBuf` or slice or cursor is not converted back into the original data type and is dropped, then its Drop impl will call the dtor function which should do the conversion and drop the underlying type.

**Comment by FrankReh** [comment]
Thanks! I hadn't appreciated the existence of `into_vec`.

Yes, my ramblings weren't well structured. The `OwnedBuf` lifecycle is clear.

But your response to my question gets me starting to understand the `unsafe Allocator` trait better, so progress. Now I'm wondering about some memory pool schemes that `tokio-uring` already has, as in `fixed buffers` and will be getting, `buffer rings` for example, and how getting them to implement `Allocator` would let their buffers be converted to `Vec<u8>` also. And slipping an `OwnedBuf` into the mix then becomes trivial.

**Comment by FrankReh** [comment]
I'm not sure if the design is creating symmetry between `Vec<u8>` and `OwnedBuf`, or if the drop function that comes from `RawVec<u8>` is somehow different than what the `Allocator's` deallocate is requiring of a stock `OwnedBuf`.

Why is `OwnedBuf`'s `into_vec` labeled unsafe? Is it only safe to use `into_vec` if the backing store started as a `Vec<u8>`?
